version: "3"
services:
    service_coordinates:
        container_name: Coordinates_Flask_Server
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TZ: "America/Sao_Paulo"
        ports:  
          - "7373:7373"